Repository Coder-Jat/hacktoberfest2022, pull requests merged in 2022-10, with the labels that each got.

#2 Created A Menu To Order Fast Food
  C/Ordering Fast Foods
Labels: good first issue, hacktoberfest-accepted

#3 Created a Food Ordering System
  C++/Food_Ordering_System.cpp
Labels: good first issue, hacktoberfest-accepted

#4 Created A grade system according to the marks
  C/Grading_System.c
Labels: good first issue, hacktoberfest-accepted

#5 Swapping of two numbers
  C/Swapping.Two.Numbers.c
Labels: hacktoberfest-accepted

#6 Stop On Odd Input
  C/Stoponodd.c
Labels: hacktoberfest-accepted

#7 Update Swapping.Two.Numbers.c
  C/Swapping.Two.Numbers.c
Labels: hacktoberfest-accepted, Improved-Code

#11 Updating Readme.md file
  README.md
Labels: hacktoberfest-accepted

#9 bubble sort
  C++/bubble-sort.cpp
Labels: hacktoberfest-accepted

#17 Create Adding_GST_to_price
  C/Adding_GST_to_price.c
Labels: good first issue, hacktoberfest-accepted, Improved-Code

#23 Create Recipe.c
  C/Recipe.c
Labels: good first issue, hacktoberfest-accepted

#26 Create Function_Overloading_cpp
  C++/Function_Overloading.cpp
Labels: good first issue, hacktoberfest-accepted

#20 Added binary-search in cpp
  C++/binary-search.cpp
Labels: hacktoberfest-accepted, Improved-Code

#35 Added triangle app in c++ folder
  C++/triangle.cpp
Labels: hacktoberfest-accepted

#37 I have added a code in cpp for tictactoe.
  C++/a.exe
  C++/tictactoe.cpp
Labels: hacktoberfest-accepted

#18 Added basicmaths file c++
  C++/basicmaths.cpp
Labels: hacktoberfest-accepted

#25 Iterate n terms without loops (backtracking)
  C++/backtracking.cpp
Labels: hacktoberfest-accepted
